[package]
name = "web-server-adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-server-domain = { path = "../web-server-domain" }
async-trait = "0.1.53"
